name: E2E tests

on:
  push:
    branches: [ main, master, next ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run playwright tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Bundle library
        run: npm run build

      - name: Get playwright version
        id: playwright-version
        run: echo "version=$(cat ./package-lock.json | jq -re '.packages["node_modules/@playwright/test"].version')" >> $GITHUB_OUTPUT

      - name: Run tests
        run: HOME=/root npx playwright test --config ./tests/config/playwright.config.ts

      - name: Create report comment
        id: report-summary
        uses: daun/playwright-report-summary@v2.1.2
        with:
          report-file: results.json
          job-summary: true
