name: E2E tests

on:
  push:
    branches: [ main, master, next ]
  pull_request:
  workflow_dispatch:

jobs:
  playwright:
    name: 'Run Playwright Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Bundle library
        run: npm run build

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npx playwright test --config ./tests/config/playwright.config.ts
